# Network/connectivity defaults:
# Update when still unmodified from previous known state, preserve local edits.

replace_if_unmodified /etc/default/otbr-agent optional
replace_if_unmodified /etc/ssh/sshd_config.d/99-iotgw.conf
replace_if_unmodified /etc/NetworkManager/conf.d/10-wifi-backend.conf
replace_if_unmodified /etc/NetworkManager/system-connections/br0.nmconnection
replace_if_unmodified /etc/NetworkManager/system-connections/eth0-slave-br0.nmconnection
