[system]
compatible=@COMPATIBLE@
bootloader=uboot
data-directory=/data/

[keyring]
path=/etc/rauc/ca.cert.pem

[streaming]
# mTLS client authentication for OTA server
# Run streaming helper as dedicated OTA user
sandbox-user=ota
tls-cert=/etc/ota/device.crt
tls-key=/etc/ota/device.key
tls-ca=/etc/ota/ca.crt
# Send device info as HTTP headers
send-headers=boot-id;machine-id;transaction-id

[slot.rootfs.0]
device=/dev/mmcblk0p2
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/mmcblk0p3
type=ext4
bootname=B
