# SPDX-License-Identifier: MIT
# TPM-specific runtime additions for ota-updater.service

[Service]
# Allow ota-updater to access /dev/tpmrm0 via group policy.
SupplementaryGroups=iotgwtpm
PrivateDevices=false
