[engine]
cgroup_manager = "systemd"
events_logger = "journald"
runtime = "crun"

[containers]
log_driver = "journald"
pids_limit = 4096
tz = "local"
ipcns = "private"
cgroups = "enabled"

[network]
network_backend = "netavark"
